name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew :backend:build

    - name: Run Tests
      run: ./gradlew :backend:test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/build/reports/tests/

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Checkstyle
      run: ./gradlew :backend:checkstyleMain :backend:checkstyleTest

  native-build:
    name: Native Build
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    outputs:
      ecr-registry: ${{ steps.login-ecr.outputs.registry }}
      image-tag: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Native Image
      run: ./gradlew :backend:build -Dquarkus.package.type=native -Dquarkus.native.container-build=true

    - name: Build Docker Image
      run: |
        cd backend
        docker build -f src/main/docker/Dockerfile.native -t quarkus/robot-wars-backend-native .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: af-south-1
        web-identity-token-file: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Docker Image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: robot-wars-backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag quarkus/robot-wars-backend-native $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag quarkus/robot-wars-backend-native $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [native-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: af-south-1
        web-identity-token-file: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ vars.EC2_USER || 'ec2-user' }}
        EC2_HOST: ${{ vars.EC2_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        ECR_REGISTRY: ${{ needs.native-build.outputs.ecr-registry }}
        ECR_REPOSITORY: robot-wars-backend
        IMAGE_TAG: ${{ needs.native-build.outputs.image-tag }}
        CONTAINER_NAME: ${{ vars.CONTAINER_NAME || 'robot-wars-backend' }}
        CONTAINER_PORT: ${{ vars.CONTAINER_PORT || '8080' }}
        AWS_REGION: af-south-1
      run: |
        # Create SSH key file
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
        
        # Get ECR login token
        ECR_TOKEN=$(aws ecr get-login-password --region $AWS_REGION)
        
        # Deploy to EC2 instance
        ssh -i ssh_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
          # Set AWS region for the session
          export AWS_DEFAULT_REGION=$AWS_REGION
          
          # Login to ECR using the token from GitHub Actions
          echo "$ECR_TOKEN" | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Pull the latest image
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Stop and remove existing container if it exists
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
          # Run new container
          docker run -d \
            --name $CONTAINER_NAME \
            -p $CONTAINER_PORT:8080 \
            --restart unless-stopped \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Clean up unused images
          docker image prune -f
        EOF
        
        # Clean up SSH key
        rm ssh_key
